### Solution to the January 2023 Jane Street puzzle: Lesses More


### https://www.janestreet.com/puzzles/lesses-more-index/

In [5]:
import numpy as np
from scipy import linalg

In [327]:
def midpoints(x):
    a,b,c,d = x[0],x[1],x[2],x[3]
    return np.abs(np.array([a-d,a-b,b-c,c-d]))

def f(x):
    y = midpoints(x)
    z = np.zeros(4)
    n = 1
    while not np.array_equal(y,z):
        y = midpoints(y)
        n += 1
    return n + 1

A brute force approach is not feasible as the size of the search space is $10^{28}$.

Without loss of generality, we can assume $a \geq b \geq c \geq d$.

For an input $x^{(0)} = [a,b,c,d]^T$, the next square will be $x^{(1)} = [a-d,a-b,b-c,c-d]^T$

Define a linear operator $A$ such that $Ax^{(0)} = x^{(1)}$.

 $A =\left[\begin{array}{ccc}
1 & 0 & 0 & -1\\
1 & -1 & 0 & 0\\
0 & 1 & -1 & 0\\
0 & 0 & 1 & -1 
\end{array}\right]$

It can be seen that for any $x^{(0)}$ which is not monotonically decreasing such that $a > b > c > d$, it is true that $x^{(7)} = A^7x^{(0)} = [0,0,0,0]$

For large total number of squares $f$, we require $x^{(0)}$ to be monotonically decreasing.

If the number of operations is $n = f - 1$, we can see that for squares requiring $n > 7$, for any $m \leq n - 7$:

$x^{(m)} = A^mx^{(0)}$ is monotonically decreasing and the largest element is the sum of the other three.



In [203]:
# Long termination times require a>b>c>d.

A = np.array([
    [1, 0, 0, -1],
    [1, -1, 0, 0],
    [0, 1, -1, 0],
    [0, 0, 1, -1]
])

evs = linalg.eigvals(A)

print("Eigenvalues\n",eig)

ev = np.real(8.39286755e-01+0.j)

Eigenvalues
 [ 8.39286755e-01+0.j         -4.87457297e-16+0.j
 -1.41964338e+00+0.60629073j -1.41964338e+00-0.60629073j]


We can see there is only one non-trivial real eigenvalue $\lambda \approx 0.839286755$

This is an important result as $A$ can operate on it's real eigenvectors any amount of times without reducing it to the zero 4-vector.

$A^n[(1+\lambda)^3,(1+\lambda)^2,(1+\lambda), 1] = \lambda^n [(1+\lambda)^3,(1+\lambda)^2,(1+\lambda), 1]$

Now, our search space has been vastly reduced as we only have to look for a, b, c, d between 1 and 10,000,000 where $\frac{a}{b}=\frac{b}{c}=\frac{c}{d}\approx (1+\lambda)$.

As we are also looking for the minimum of $a + b + c + d$, due to linearity, we can look at solutions of the form $ \phi[(1+\lambda)^3, (1+\lambda)+1, 1, 0]$ where $\phi$ is an integer.

In [345]:
u = np.array([(1+ev)**3,(1+ev)+1,1,0])
tol = 1e-2 * np.ones(4)
limit = int(10000000 / (1+ev)**3)
s = {}
M = 0

for phi in range(1, limit + 1 ):
    x = phi * u
    res = np.abs(x-np.round(x))
    if np.all(res < tol):
        y = np.round(x)
        if f(y) > M:
            M = f(y)
            s[M] = y

print(s[M])

[8646064. 3945294. 1389537.       0.]


The solution is $8646064;3945294;1389537;0$ which produces $44$ squares.